let data = {
  "order_id": "PX5GFJX3GT",
  "order_date": "2022-03-09 17:21",
  "channel_id": "",
  "comment": "",
  "company_name": "",
  "billing_customer_name": "Haider Hatim Nakara",
  "billing_last_name": "asfs",
  "billing_address": "Hoor manzil,samuel street ,4xlane, 2nd floor, room no 13,khadak mumbai 400009",
  "billing_address_2": "",
  "billing_city": "Mumbai",
  "billing_pincode": "400009",
  "billing_state": "Maharashtra",
  "billing_country": "India",
  "billing_email": "haider.nakara@gmail.com",
  "billing_phone": "702430367",
  "billing_alternate_phone": "",
  "shipping_is_billing": True,
  "shipping_customer_name": "",
  "shipping_last_name": "",
  "shipping_address": "",
  "shipping_address_2": "",
  "shipping_city": "",
  "shipping_pincode": "",
  "shipping_country": "",
  "shipping_state": "",
  "shipping_email": "",
  "shipping_phone": "",
  "payment_method": "PrePaid",
  "shipping_charges": "",
  "giftwrap_charges": "",
  "transaction_charges": "",
  "total_discount": "",
  "sub_total": 100,
  "length": 10,
  "breadth": 10,
  "height": 10,
  "weight": 10,
  "ewaybill_no": "",
  "customer_gstin": "",
  "invoice_number": "",
  "order_type": "",
  "order_items": [
    { "name": "Shoes", "sku": "", "units": 1, "selling_price": 137, "discount": "", "tax": "", "hsn": 15445 }
  ],
};
